### ISSUE TITLE
admin not accessible on nginx

### ISSUE THREAD

**Issue by smpcasgit** [dignajar/bludit#47] opened 2015-09-29 08:26 UTC
Bludit v0.2
Stable version.
Release date: 2015-09-21

rewrite rule not working

charset utf-8;
location ~ ^/content/(.*)\.(txt)$ {
}
location / {
if (!-e $request_filename){
rewrite ^/(.*) /index.php break;
}
}

this nginx rewrite rule works

try_files $uri $uri/ /index.php?$args;

but login and daschboard access only
/admin/login
/admin/dashboard

**Comment by patschi** [comment] 2015-10-07 08:18
Could you try the latest nginx configuration in the recent updated docu page?
http://docs.bludit.com/en/troubleshooting/missing-htaccess-file-err201#nginx

This rewrite rules should do the job.

**Comment by gabrielrm** [comment] 2015-10-19 15:23
Hi, I've tried the latest nginx configuration mentioned in bludit docs and I've get this error using bludit version 0.3.

> Notice: Undefined index: — in /var/www/bludit/kernel/boot/rules/70.pages.php on line 129
Fatal error: Call to a member function position() on a non-object in /var/www/bludit/kernel/boot/rules/70.pages.php on line 129 

Obvious I don't know how to rewrite rules.
Thank you.

**Comment by patschi** [comment] 2015-10-19 15:28
I'm not familiar with the source of Bludit, but this kinda looks like a PHP issue and not anything related to nginx. Did you use the ZIP archive from http://www.bludit.com/bludit_latest.zip and uploaded it without changes on your server?

**Comment by gabrielrm** [comment] 2015-10-19 15:35
Yes, exactly bludit_katest.zip, unzip and chown -R www-data:www-data /var/www/bludit. It past the instalation, load the "First post" page and using admin area link got the error.

**Comment by dignajar** [comment] 2015-10-24 20:53
Hi, I try the configuration and works fine.
The error undefined index, is a bug, but I can't reproduce the error, have you pages created with parents?

**Comment by dignajar** [comment] 2015-10-29 03:50
I found the bug!! it fixed now.

I added the nginx config file and some info here, http://docs.bludit.com/en/web-servers/nginx

**Comment by gabrielrm** [comment] 2015-10-31 07:33
I use bludit last version and nginx config from docs and the error from nginx log is:
> 2015/10/30 20:28:01 [error] 9650#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: — in /var/www/bludit/kernel/boot/rules/70.pages.php on line 129
PHP message: PHP Fatal error:  Call to a member function position() on a non-object in /var/www/bludit/kernel/boot/rules/70.pages.php on line 129" while reading response header from upstream, client: 192.168.1.2, server: blog.server.address, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "blog.server.address", referrer: "http://blog.server.address/"

The error in browser is the same. 
>Notice: Undefined index: — in /var/www/bludit/kernel/boot/rules/70.pages.php on line 129
>
Fatal error: Call to a member function position() on a non-object in /var/www/bludit/kernel/boot/rules/70.pages.php on line 129

I have to say that the error occurs accessing any first link, "Home" or "admin area" and after restarting php service is loading the "First post" page.

**Comment by dignajar** [comment] 2015-10-31 17:33
gabrielrm,
please update this file https://github.com/dignajar/bludit/blob/master/kernel/boot/rules/70.pages.php or download the last version from github, because the version 0.4 have this bug.
thanks

**Comment by gabrielrm** [comment] 2015-11-01 12:03
Thank you very much! Now is working ok.
Have a nice weekend!

**Closed** 2015-11-05 03:03 UTC
